# sudo: required

language: go

go:
  - tip

go_import_path: github.com/zekroTJA/shinpuru

addons:
  ssh_known_hosts: zekro.de

script:
  - bash ./ci/travis.sh

# before_install:
#   - openssl aes-256-cbc -K $encrypted_37839d6e8267_key -iv $encrypted_37839d6e8267_iv
#     -in ./ci/deploy_rsa.enc -out deploy_rsa -d
#   - eval "$(ssh-agent -s)"
#   - chmod 600 deploy_rsa
#   - ssh-add deploy_rsa

after_success: |
  if [ -n "$GITHUB_TOKEN" ]; then
    git clone https://zekroTJA:$GITHUB_TOKEN@github.com/zekroTJA/shinpuru.wiki.git
    mv docs/commandsManual.md shinpuru.wiki/Commands.md
    git -C ./shinpuru.wiki add .
    git -C ./shinpuru.wiki -c user.name="travis" -c user.email="travis" commit -m "automatically updated commands list"
    git -C ./shinpuru.wiki push
  fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: FzDdGC6yPmWlhJG8K5CuPUDbi+vPy6Fzk/60Yx/dfTFrtupQNIRA6ou2w4/Xli60NLV2PdBhjrG8REnUOJLneR/+Kvbvw/WZP5v3PIMDvmLMdt9lflcHRY60dH8w1CZ4zOc8Mob6sc0c9BUOFskw/tgx+HZXweD2SgvY+jYXA7MVmQPejOuIssgcL93lWTM9VH9/uESYbykKzSRjOvcSnB4Yt9UYZHaMI8n0XFo+ZMmkiknUdFtFP0racgj/QJjvzH7MWz32ax8jerxPGhUPg9wzKmlwNjwiPtJdDihWvgQ23xnpLaD/0TqD26sJ6ScIB6TjsCWjZuPVPLGvbBjq3BcQQ2zB7zy/zRE2BuaSABdmvScNLo1YM6QEtGemDm0oKwbAalbpQX1pIF2S1oQOgVD1knabFwZT+ATMQmoO9t35J+qzmF2yPPiFm0MXZ1ztIij+kFfugn8DdaOZtvK1Lkg+TttK573TnYTa1WwwACbDrnwvRS6Qn/GCGUHuczOZ+Nbid0JrQ39/YWIR7hQRukwZmXqxnDSN1xeZwR2tUgU/QLH3WrqRa4qMckLQwvY9bIWyo7ydm1lZXRcecYTHA5XDrvMO64ODXOq52z2/VbTmGZIJZ+PFsfm6XvKPhzAGSBV9QsyGUbkj9HuScnCfqiaYzX2Wz7kNUkivuGRTcvA=
  file:
    - bin/sha256sums
    - bin/shinpuru_linux_arm
    - bin/shinpuru_linux_amd64
    - bin/shinpuru_darwin_amd64
    - bin/shinpuru_windows_amd64.exe
  on:
    tags: true